---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: datanode:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: datanode-env
      terminationGracePeriodSeconds: 180